#!/bin/bash

BRIGHTNESS=`sudo cat /sys/class/backlight/intel_backlight/brightness`
MAX_BRIGHTNESS=`sudo cat /sys/class/backlight/intel_backlight/max_brightness`
HUNDRED_PERCENT=expr `$BRIGHTNESS / $MAX_BRIGHTNESS * 1
